from django.urls import path

from . import views

urlpatterns = [
    path("", views.projects_view),
    path(
        "projects/<str:project_id>/",
        views.project_detail_view,
    ),
    path("api/projects/", views.projects_api),
    path(
        "api/projects/<str:project_id>/docs",
        views.project_docs_api,
    ),
    path(
        "api/projects/<str:project_id>/docs/count",
        views.project_docs_count_api,
    ),
    path(
        "api/projects/<str:project_id>/labels",
        views.project_labels_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/create",
        views.create_label_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/<str:label_id>/activate",
        views.set_active_label_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/<str:label_id>/rename",
        views.rename_label_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/<str:label_id>/stats",
        views.label_stats_api,
    ),
    path(
        "api/projects/<str:project_id>/prompts",
        views.project_prompts_api,
    ),
    path(
        "api/projects/<str:project_id>/prompts/create",
        views.create_prompt_api,
    ),
    path(
        "api/projects/<str:project_id>/prompts/<str:prompt_id>/update",
        views.update_prompt_api,
    ),
    path(
        "api/projects/<str:project_id>/prompts/<str:prompt_id>/reset",
        views.reset_prompt_api,
    ),
    path(
        "api/projects/<str:project_id>/prompts/<str:prompt_id>/delete",
        views.delete_prompt_api,
    ),
    path(
        "api/projects/<str:project_id>/update",
        views.update_project_api,
    ),
    path(
        "api/projects/<str:project_id>/delete",
        views.delete_project_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/<str:label_id>/delete",
        views.delete_label_api,
    ),
    path(
        "api/projects/<str:project_id>/tasks/update",
        views.update_tasks_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/<str:label_id>/threads",
        views.label_threads_api,
    ),
    path(
        "api/projects/<str:project_id>/labels/<str:label_id>/threads/create",
        views.create_thread_api,
    ),
    path(
        "api/projects/<str:project_id>/threads/<str:thread_id>/delete",
        views.delete_thread_api,
    ),
    path(
        "api/projects/<str:project_id>/threads/<str:thread_id>/messages",
        views.thread_messages_api,
    ),
    path(
        "api/projects/<str:project_id>/threads/<str:thread_id>/send",
        views.send_message_api,
    ),
]
