from django.urls import path

from . import views

urlpatterns = [
    path("", views.index_view),
    path(
        "project/<slug:project_id>/search/", views.search_view, name="search"
    ),
    path(
        "api/project/<slug:project_id>/project/",
        views.project_endpoint,
        name="project",
    ),
    path(
        "api/project/<slug:project_id>/project/update-instructions/",
        views.project_update_instructions_endpoint,
        name="project-update-instructions-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/search/",
        views.search_endpoint,
        name="search-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/labels/",
        views.labels_endpoint,
        name="labels-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/labels/update-instructions/",
        views.labels_update_instructions_endpoint,
        name="labels-update-instructions-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/labels/save-querystring/",
        views.labels_save_querystring_endpoint,
        name="labels-save-querystring-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/labels/delete-querystring/",
        views.labels_delete_querystring_endpoint,
        name="labels-delete-querystring-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/tags/",
        views.tags_endpoint,
        name="tags-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/annotate/",
        views.annotate_endpoint,
        name="annotate-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/decisions/",
        views.decisions_endpoint,
        name="decisions-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/decision/update/",
        views.decision_update_endpoint,
        name="decision-update-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/decision/delete/",
        views.decision_delete_endpoint,
        name="decision-delete-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/heuristics/",
        views.heuristics_endpoint,
        name="heuristics-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/heuristic/add/",
        views.heuristic_add_endpoint,
        name="heuristic-add-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/heuristics/apply/",
        views.heuristic_apply_endpoint,
        name="heuristic-apply-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/heuristics/set-flag/",
        views.heuristic_set_flag_endpoint,
        name="heuristic-set-flag-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/heuristics/delete/",
        views.heuristic_delete_endpoint,
        name="heuristic-delete-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/heuristics/sync-custom/",
        views.heuristics_sync_custom_endpoint,
        name="heuristics-sync-custom-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/predictor/update-trainset/",
        views.predictor_update_trainset_endpoint,
        name="predictor-update-trainset-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/predictor/update-trainset-preds/",
        views.predictor_update_trainset_preds_endpoint,
        name="predictor-update-trainset-preds-endpoint",
    ),
    path(
        "api/project/<slug:project_id>/finetunes/",
        views.finetunes_endpoint,
        name="finetunes-endpoint",
    ),
]
