# Generated by Django 6.0.3 on 2026-04-06 19:09

import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0000_custom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    django_shortuuid.fields.ShortUUIDField(
                        alphabet=None,
                        blank=True,
                        collision_check=True,
                        editable=False,
                        length=22,
                        max_length=22,
                        max_retries=10,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    django_shortuuid.fields.ShortUUIDField(
                        alphabet=None,
                        blank=True,
                        collision_check=True,
                        editable=False,
                        length=22,
                        max_length=22,
                        max_retries=10,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("text", models.TextField()),
                ("text_prefix", models.CharField(max_length=50)),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("shuffle_key", models.IntegerField()),
                ("text_hash", models.CharField(max_length=64)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "text_hash")},
            },
        ),
    ]
