# Generated by Django 5.2.7 on 2026-04-06 19:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('text_prefix', models.CharField(max_length=50)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('shuffle_key', models.IntegerField()),
                ('text_hash', models.CharField(max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['shuffle_key', 'id'], name='shuffle_key_idx'), models.Index(fields=['text_prefix'], name='text_prefix_idx', opclasses=['text_pattern_ops']), django.contrib.postgres.indexes.GinIndex(fields=['text'], name='text_trgm_idx', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(fields=('project', 'text_hash'), name='document_project_text_hash_uniq')],
            },
        ),
    ]
