# Generated by Django 5.2.7 on 2026-04-06 20:55

import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='app.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='active_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='label_project_name_uniq'),
        ),
    ]
