# Generated by Django 5.2.7 on 2026-04-06 22:03

import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_label_project_active_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.CharField(max_length=255)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='app.label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(default=dict)),
                ('num_tokens', models.IntegerField(default=0)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
