# Generated by Django 5.2.7 on 2026-04-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_label_instructions_thread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='manual_instructions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='model',
            field=models.CharField(default='gemini/gemini-3.1-pro-preview', max_length=255),
        ),
    ]
