# Generated by Django 5.2.7 on 2026-02-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_labelfinetune_finetuned_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltrainsetexample',
            name='reason',
        ),
        migrations.AddField(
            model_name='labeltrainsetexample',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainset_examples', to='app.labeldecision'),
        ),
    ]
