# Generated by Django 5.2.7 on 2026-04-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_instructions_project_manual_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manual_instructions',
        ),
    ]
