# Generated by Django 5.2.7 on 2026-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_labeltrainsetexample_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltrainsetexample',
            name='decision',
        ),
        migrations.AddField(
            model_name='labeltrainsetexample',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
