# Generated by Django 5.2.7 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_project_manual_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
