# Generated by Django 5.2.7 on 2026-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_labeltrainsetexample_decision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='inference_model',
        ),
        migrations.RemoveField(
            model_name='label',
            name='predictor_data',
        ),
        migrations.RemoveField(
            model_name='label',
            name='predictor_updated_at',
        ),
        migrations.RemoveField(
            model_name='label',
            name='teacher_model',
        ),
        migrations.RemoveField(
            model_name='label',
            name='trainset_examples_per_heuristic_bucket',
        ),
        migrations.AlterField(
            model_name='label',
            name='trainset_num_excluded',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='trainset_num_likely',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='trainset_num_neutral',
            field=models.IntegerField(default=50),
        ),
    ]
