# Generated by Django 5.2.7 on 2026-04-07 16:37

import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_thread_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDocument',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_documents', to='app.document')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_documents', to='app.label')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('label', 'document'), name='labeldocument_label_document_uniq')],
            },
        ),
    ]
