# Generated by Django 5.2.7 on 2026-02-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_label_inference_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='trainset_num_decision_neighbors',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='LabelQuerystring',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('querystring', models.TextField()),
                ('num_examples', models.IntegerField(default=30)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='querystrings', to='app.label')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
