# Generated by Django 5.2.7 on 2026-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_labeldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='model',
            field=models.CharField(default='openai/gpt-5.4', max_length=255),
        ),
    ]
