# Generated by Django 5.2.7 on 2026-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_label_trainset_num_decision_neighbors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelquerystring',
            name='num_examples',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterUniqueTogether(
            name='labelquerystring',
            unique_together={('label', 'querystring')},
        ),
    ]
