# Generated by Django 5.2.7 on 2026-04-07 18:09

import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_thread_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationAnnotation',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('skip', 'Skip')], max_length=4)),
                ('source', models.CharField(max_length=255)),
                ('label_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='app.labeldocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('label_document', 'source'), name='annotation_labeldoc_source_uniq')],
            },
        ),
    ]
