# Generated by Django 5.2.7 on 2026-04-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_classificationannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='thread',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
