# Generated by Django 5.2.7 on 2026-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_labelquerystring_num_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeldecision',
            name='added_to_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labelquerystring',
            name='added_to_sample',
            field=models.BooleanField(default=False),
        ),
    ]
