# Generated by Django 5.2.7 on 2026-04-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_thread_total_cost_thread_total_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='total_tokens',
        ),
    ]
