# Generated by Django 5.2.7 on 2026-04-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_thread_total_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_compact',
            field=models.BooleanField(default=False),
        ),
    ]
