# Generated by Django 5.2.7 on 2026-04-08 12:33

import django.db.models.deletion
import django.utils.timezone
import django_shortuuid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message_is_compact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet=None, blank=True, collision_check=True, editable=False, length=22, max_length=22, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='app.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'prompt_id'), name='prompt_project_promptid_uniq')],
            },
        ),
    ]
