# Generated by Django 5.2.7 on 2026-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='built_in',
            field=models.BooleanField(default=False),
        ),
    ]
