# Generated by Django 5.2.7 on 2026-04-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='autopilot_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.thread'),
        ),
    ]
