# Generated by Django 5.2.7 on 2026-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_label_autopilot_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autopilot_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
