# Generated by Django 5.2.7 on 2026-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_project_autopilot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='autopilot_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_input', 'Awaiting Input')], default='pending', max_length=20),
        ),
    ]
