# Generated by Django 5.2.7 on 2026-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_thread_autopilot_locked_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
