# Generated by Django 5.2.7 on 2026-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_message_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='finetune_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='label',
            name='finetune_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='label',
            name='finetune_training_args',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='label',
            name='finetuned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
